testing CI, final adjustments, cleaning up code, preparing for release
exasol/snowflake-virtual-schema pull request #2
Opened 2024-08-29 10:25 UTC by pj-spoelders

Closes #1

2024-09-27 08:15 UTC, kaklakariada reviewed
General: Indentation of Java files is broken for some files. Please run formatter for all files.

2024-09-27 08:15 UTC, kaklakariada commented on .vscode/settings.json
> +      "-Dcom.exasol.dockerdb.image=8.24.0"
```suggestion
      "-Dcom.exasol.dockerdb.image=8.31.0"
```

2024-09-27 08:15 UTC, kaklakariada commented on .vscode/settings.json
> +      "-Dtest.debug='true'",
```suggestion
      "-Dtest.debug=true",
```

2024-09-27 08:15 UTC, kaklakariada commented on README.md
Contains some broken links, e.g. `[Virtual Schemas Repository][virtual-schemas]`

2024-09-27 08:22 UTC, kaklakariada requested changes
General: Indentation of Java files is broken for some files. Please run formatter for all files.
Also I am not sure if all findings from https://github.com/exasol/snowflake-virtual-schema/pull/4 are implemented here, or do you want to implement them in another PR?

2024-09-30 08:10 UTC, pj-spoelders commented
I seem to have missed a bunch of the other review's comments .. working on it.

2024-09-30 13:30 UTC, pj-spoelders commented on README.md
Fixed

2024-09-30 13:30 UTC, pj-spoelders commented on .vscode/settings.json
> +      "-Dtest.debug='true'",
Removed it altogether

2024-10-01 14:50 UTC, kaklakariada approved these changes

2024-10-01 15:00 UTC, merged